apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: tools
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  storageClassName: "oci"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi